config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  resources :restaurants, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
    resources :tags, only: [ :new, :create ]
    resources :menus, only: [:new, :create, :show, :edit, :update ]
    resources :orders, only: [:index, :new, :create, :show ] 
    resources :workers, only: [ :index, :new, :create ]
  end

  resources :restaurant_schedules, only: [ :new, :create, :show, :edit, :update ]

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member 
    post 'active', on: :member
    resources :dish_portions, only: [ :new, :create, :show ] do
      resources :dish_previous_prices, only: [ :create ]
    end
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member
    post 'active', on: :member
    resources :beverage_portions, only: [ :new, :create, :show ] do 
      resources :beverage_previous_prices, only: [ :create ]
    end
  end

  resources :carts, only: [ :show ] do
    post 'add_dish', on: :member
    post 'remove_dish', on: :member
    post 'add_beverage', on: :member
    post 'remove_beverage', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :restaurants, param: :code, only: [ ] do
        resources :orders, param: :code, only: [ :index, :show ] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :restaurant
  has_many :beverage_portions
  has_many :items
  has_many :menus, through: :items
  has_one_attached :image
  
  validates :name, :description, :calories, presence: true

  enum status: { inactive: 0, active: 2 }

end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  before_action :auth_admin
  before_action :register_a_restaurant
  before_action :set_beverage_and_check_restaurant, only: [ :show , :edit ,:update, :destroy, :inactive, :active ]

  def index
    @beverages = current_admin.restaurant.beverages
  end

  def new
    @beverage = Beverage.new
  end

  def create
    @beverage = Beverage.new(beverage_params)
    @beverage.restaurant = current_admin.restaurant
    @beverage.image.attach(params[:beverage][:image]) 
    if @beverage.save
    redirect_to beverages_path, notice: 'Bebida de Restaurante cadastrado'

    else
      @beverage.restaurant = nil
      flash.now[:alert] = 'BEbida de Restaurante não cadastrado'
      render 'new', status: :unprocessable_entity
    end  
  end

  def show;  end

  def edit; end

  def update
    if @beverage.update(beverage_params)
      redirect_to beverage_path(@beverage), notice: 'Bebida de Restaurante editado'
      if params[:beverage][:image].present?
        @beverage.image.attach(params[:beverage][:image])         
      end        
    else
      flash.now[:alert] = 'Bebida de Restaurante não editado'
        render 'edit', status: :unprocessable_entity
    end  
  end

  def destroy
    @beverage.destroy
    redirect_to dishes_path, notice: "Bebida removido com sucesso"
  end

  def inactive
    @beverage.inactive!
    redirect_to @beverage
  end

  def active
    @beverage.active!
    redirect_to @beverage
  end

  private
  def beverage_params
    params.require(:beverage).permit(:name, :description, :calories)
  end

  def set_beverage_and_check_restaurant
    @beverage = Beverage.find(params[:id])
    if @beverage.restaurant != current_admin.restaurant
      redirect_to root_path, alert: "Você não possui acesso a este bebida"
    end
  end
end

app/views/beverages/_form.html.erb
<%= form_with(model: @beverage, class: "space-y-8") do |f| %>
  <div>
    <%= f.label :name, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :name, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :description, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :description, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :calories, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.number_field :calories, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :image, 'Foto', class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.file_field :image, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.submit 'Enviar', class: "w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
  </div>
<% end %>

app/views/beverages/edit.html.erb
<section class="bg-slate-500">
  <div class="max-w-screen-md mx-auto w-3/4 px-4 py-4" >
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Editar Bebida</h2>
      <%= render 'form' %>  
  </div>
</section>

app/views/beverages/index.html.erb
<div class="m-4 relative overflow-x-auto flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                  Nome
                </th>
                <th scope="col" class="px-6 py-3">
                  Calorias
                </th>
            </tr>
        </thead>
        <tbody>
           <% @beverages.each do |beverage| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <%=link_to beverage.name, beverage_path(beverage), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"  %>
                </td>
                <td class="px-6 py-4">
                  <%= beverage.calories %>
                </td>                
              </tr>
            <% end %>
        </tbody>
    </table>
    <br/>
    
  <div>  
    <%= link_to 'Cadastrar', new_beverage_path, class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
  </div>
</div>






  

app/views/beverages/new.html.erb
<section class="bg-slate-500" id="dish">
  <div class="max-w-screen-md mx-auto w-3/4 px-4 py-4">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Cadastrar Bebida</h2>
      <% if @beverage.errors.any? %>
        <ul>
          <% @beverage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= render 'form' %>  
  </div>
</section>

app/views/beverages/show.html.erb
<section class="bg-slate-500">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white">Bebida: <%= @beverage.name  %> </h2>
    <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-blue">         
      <% if @beverage.image.attached? %>
        <img src="<%= url_for(@beverage.image) %>" alt="Imagem" class="object-contain h-48 w-96">
      <% end %>
    </p>    
    <dl>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Descrição:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @beverage.description %></dd>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Calorias:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @beverage.calories %> kcal</dd>
    </dl>
    <dl class="flex items-center space-x-6">
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Status:</dt>
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= I18n.translate(@beverage.status) %></dd>
      </div>
    </dl>
      <div>
   <% @beverage.beverage_portions.each do |beverage_portion| %>
    <%= link_to beverage_portion.description, beverage_beverage_portion_path(@beverage, beverage_portion) %> preço: <%= beverage_portion.price %>
  <% end %>
      </div>
      <br/>
      <div class="flex items-center space-x-4">
        <% if @beverage.active? %>
          <%= button_to 'Desativar', inactive_beverage_path(@beverage), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <% else %>
          <%= button_to 'Ativar', active_beverage_path(@beverage), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <% end %>
        <%= link_to 'Editar', edit_beverage_path(@beverage), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <%= button_to 'Remover', beverage_path(@beverage), method: :delete,  class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <%= link_to 'Adicionar porção', new_beverage_beverage_portion_path(@beverage), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
      </div>
    <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
  </div>
</section>