config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  resources :restaurants, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
    resources :tags, only: [ :new, :create ]
    resources :menus, only: [:new, :create, :show, :edit, :update ]
    resources :orders, only: [:index, :new, :create, :show ] 
    resources :workers, only: [ :index, :new, :create ]
  end

  resources :restaurant_schedules, only: [ :new, :create, :show, :edit, :update ]

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member 
    post 'active', on: :member
    resources :dish_portions, only: [ :new, :create, :show ] do
      resources :dish_previous_prices, only: [ :create ]
    end
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member
    post 'active', on: :member
    resources :beverage_portions, only: [ :new, :create, :show ] do 
      resources :beverage_previous_prices, only: [ :create ]
    end
  end

  resources :carts, only: [ :show ] do
    post 'add_dish', on: :member
    post 'remove_dish', on: :member
    post 'add_beverage', on: :member
    post 'remove_beverage', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :restaurants, param: :code, only: [ ] do
        resources :orders, param: :code, only: [ :index, :show ] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderable_dishes
  has_many :dish_portions, through: :orderable_dishes
  has_many :orderable_beverages
  has_many :beverage_portions, through: :orderable_beverages


  def total
    self.orderable_dishes.to_a.sum { |orderable_dish| orderable_dish.total} + self.orderable_beverages.to_a.sum { |orderable_beverage| orderable_beverage.total}
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_dish
    @dish_portion = DishPortion.find_by(id: params[:id])
    
    
    quantity = params[:quantity].to_i
    current_orderable_dish = @cart.orderable_dishes.find_by(dish_portion_id: @dish_portion.id)
  
    if current_orderable_dish && quantity > 0
      if current_orderable_dish.update(quantity: quantity)
        redirect_back_or_to root_path, notice: 'Pedido adicionado ao carinho'
      else
        redirect_back_or_to root_path, notice: 'Quantidade deve ser maior a 0'
      end
    else
      @orderable_dish = @cart.orderable_dishes.build(dish_portion_id: @dish_portion.id, quantity: quantity)
      if @orderable_dish.save
        redirect_back_or_to root_path, notice: 'Pedido adicionado ao carinho'
      else
        redirect_back_or_to root_path, notice: 'Quantidade deve ser maior a 0'
      end
    end    
  end

  def remove_dish
    OrderableDish.find_by(id: params[:id]).destroy
    redirect_back_or_to root_path
  end

  def add_beverage
    @beverage_portion = BeveragePortion.find_by(id: params[:id])
    
    quantity = params[:quantity].to_i
    current_orderable_beverage = @cart.orderable_beverages.find_by(beverage_portion_id: @beverage_portion.id)
    if current_orderable_beverage && quantity > 0
      if current_orderable_beverage.update(quantity: quantity)
        redirect_back_or_to root_path, notice: 'Pedido adicionado ao carinho'
      else
        redirect_back_or_to root_path, notice: 'Quantidade deve ser maior a 0'
      end
    else
      @orderable_beverage = @cart.orderable_beverages.build(beverage_portion_id: @beverage_portion.id, quantity: quantity)
      if @orderable_beverage.save
        redirect_back_or_to root_path, notice: 'Pedido adicionado ao carinho'
      else
        redirect_back_or_to root_path, notice: 'Quantidade deve ser maior a 0'
      end
    end   
  end

  def remove_beverage
    OrderableBeverage.find_by(id: params[:id]).destroy
    redirect_back_or_to root_path
  end
end

app/views/carts/_cart.html.erb
<h1> Carinho </h1>
<div id="cart">
  <% if @cart.orderable_dishes.count > 0 || @cart.orderable_beverages.count > 0 %>
    <%= render 'carts/orderables' %>
    <p> Total: <%= @cart.total%> </p> <br/> <%= link_to 'Enviar Pedido', new_restaurant_order_path(@restaurant), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'%>      
  <% else %>
    <p>Carinho vazio</p>
  <% end %>
</div>

app/views/carts/_orderables.html.erb
<% @cart.orderable_dishes.each do |orderable_dish|  %>
  <% dish_portion = orderable_dish.dish_portion%>
  <div style="display:flex;space-between;margin: 0em 5em;">
    <%= dish_portion.dish.name %>
    <%= dish_portion.description %>
    <%= dish_portion.price %> x <%= orderable_dish.quantity %>
    <%= form_with(url: add_dish_cart_path(dish_portion)) do |f| %>
      <%= f.hidden_field :id, value: dish_portion.id %>
      <%= f.number_field :quantity, class: 'w-1/2 bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none' %>
      <%= f.submit 'Adicionar ao pedido', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
    <%= form_with(url: remove_dish_cart_path(orderable_dish)) do |f| %>
      <%= f.hidden_field :id, value: orderable_dish.id %>
      <%= f.submit 'X', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
    <strong>Total: <%= orderable_dish.total %></strong>    
  </div>
<% end %>

<% @cart.orderable_beverages.each do |orderable_beverage|  %>
  <% beverage_portion = orderable_beverage.beverage_portion%>
  <div style="display:flex;space-between;margin: 0em 5em;">
    <%= beverage_portion.beverage.name %>
    <%= beverage_portion.description %>
    <%= beverage_portion.price %> x <%= orderable_beverage.quantity %>
    <%= form_with(url: add_beverage_cart_path(beverage_portion)) do |f| %>
      <%= f.hidden_field :id, value: beverage_portion.id %>
      <%= f.number_field :quantity, class: 'w-1/2 bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none' %>
      <%= f.submit 'Adicionar ao pedido', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
    <%= form_with(url: remove_beverage_cart_path(orderable_beverage)) do |f| %>
      <%= f.hidden_field :id, value: orderable_beverage.id %>
      <%= f.submit 'X', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
    <strong>Total: <%= orderable_beverage.total %></strong>
    
  </div>
<% end %>