config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  resources :restaurants, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
    resources :tags, only: [ :new, :create ]
    resources :menus, only: [:new, :create, :show, :edit, :update ]
    resources :orders, only: [:index, :new, :create, :show ] 
    resources :workers, only: [ :index, :new, :create ]
  end

  resources :restaurant_schedules, only: [ :new, :create, :show, :edit, :update ]

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member 
    post 'active', on: :member
    resources :dish_portions, only: [ :new, :create, :show ] do
      resources :dish_previous_prices, only: [ :create ]
    end
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member
    post 'active', on: :member
    resources :beverage_portions, only: [ :new, :create, :show ] do 
      resources :beverage_previous_prices, only: [ :create ]
    end
  end

  resources :carts, only: [ :show ] do
    post 'add_dish', on: :member
    post 'remove_dish', on: :member
    post 'add_beverage', on: :member
    post 'remove_beverage', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :restaurants, param: :code, only: [ ] do
        resources :orders, param: :code, only: [ :index, :show ] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :dish_portions
  has_many :taggings
  has_many :items
  has_many :tags, through: :taggings
  has_many :menus, through: :items
  has_one_attached :image

  validates :name, :description, :calories, presence: true
  enum status: { inactive: 0, active: 2 }
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :auth_admin
  before_action :register_a_restaurant
  before_action :set_dish_and_check_restaurant, only: [:show, :edit, :update, :destroy, :inactive, :active]
  def index
    @dishes = current_admin.restaurant.dishes
  end  

  def new
    @restaurant = current_admin.restaurant
    @tag = Tag.new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.restaurant = current_admin.restaurant
    @dish.image.attach(params[:dish][:image]) 
    if @dish.save
      
    redirect_to dishes_path, notice: 'Prato de Restaurante cadastrado'

    else
      @dish.restaurant = nil
      flash.now[:alert] = 'Prato de Restaurante não cadastrado'
      @restaurant = current_admin.restaurant
      @tag = Tag.new
      render 'new', status: :unprocessable_entity
    end  
  end

  def show;  end

  def edit
    @restaurant = current_admin.restaurant
    @tag = Tag.new
  end

  def update
    if @dish.update(dish_params)
      redirect_to dish_path(@dish), notice: 'Prato de Restaurante editado'
      if params[:dish][:image].present?
        @dish.image.attach(params[:dish][:image])         
      end        
    else
      flash.now[:alert] = 'Prato de Restaurante não editado'
        render 'edit', status: :unprocessable_entity
    end  
  end

  def destroy
    @dish.destroy
    redirect_to dishes_path, notice: "Prato removido com sucesso"
  end

  def inactive
    @dish.inactive!
    redirect_to @dish
  end

  def active
    @dish.active!
    redirect_to @dish
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :description, :calories, tag_ids: [])
  end

  def set_dish_and_check_restaurant
    @dish = Dish.find(params[:id])
    if @dish.restaurant != current_admin.restaurant
      redirect_to root_path, alert: "Você não possui acesso a este prato"
    end
  end
end

app/views/dishes/_form.html.erb
<%= form_with(model: @dish, class: "space-y-8") do |f| %>
  <div>
    <%= f.label :name, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :name, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :description, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :description, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :calories, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.number_field :calories, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :tag_ids, 'Características',  class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.select :tag_ids, current_admin.restaurant.tags.collect { |tag| [tag.description, tag.id] }, { multiple: true } , class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <section>
    <%= render template:'tags/new' %>
  </section>
  <div>
    <%= f.label :image, 'Foto', class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.file_field :image, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.submit 'Enviar', class: "w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<section class="bg-slate-500" id="dish">
  <div class="max-w-screen-md mx-auto w-3/4 px-4 py-4" >
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Editar Prato</h2>
      <%= render 'form' %>  
  </div>
</section>

app/views/dishes/index.html.erb
<div class="m-4 relative overflow-x-auto flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                  Nome
                </th>
                <th scope="col" class="px-6 py-3">
                  Calorias
                </th>
            </tr>
        </thead>
        <tbody>
            <% @dishes.each do |dish| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <%= link_to dish.name, dish_path(dish), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"  %>
                </td>
                <td class="px-6 py-4">
                  <%= dish.calories %>
                </td>                
              </tr>
            <% end %>
        </tbody>
    </table>
    <br/>
    
  <div>  
    <%= link_to 'Adicionar Carateristica', new_restaurant_tag_path(current_admin.restaurant), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
    <%= link_to 'Cadastrar', new_dish_path, class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
  </div>
</div>






  

app/views/dishes/new.html.erb
<section class="bg-slate-500" id="dish">
  <div class="max-w-screen-md mx-auto w-3/4 px-4 py-4">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Cadastrar Prato</h2>
      <% if @dish.errors.any? %>
        <ul>
          <% @dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= render 'form' %>  
  </div>
</section>

app/views/dishes/show.html.erb
<section class="bg-slate-500">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white">Prato: <%= @dish.name  %></h2>
    <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-blue">         
      <% if @dish.image.attached? %>
        <img src="<%= url_for(@dish.image) %>" alt="Imagem" class="object-contain h-48 w-96">
      <% end %></p>    
    <dl>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Descrição:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @dish.description %></dd>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Calorias:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @dish.calories %> kcal</dd>
    </dl>
    <dl class="flex items-center space-x-6">
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Status:</dt>
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= I18n.translate(@dish.status) %></dd>
      </div>
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Caracteristicas:</dt>
        
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400">
          <% @dish.tags.each do |tag| %>
            <%= tag.description %>
          <% end %>
        </dd>  
      </div>
    </dl>
      <div>
      <% @dish.dish_portions.each do |dish_portion| %>
        <%=link_to dish_portion.description, dish_dish_portion_path(@dish, dish_portion) %> preço: <%= dish_portion.price %>
      <% end %>
      </div>
      <br/>
      <div class="flex items-center space-x-4">
        <% if @dish.active? %>
          <%= button_to 'Desativar', inactive_dish_path(@dish), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <% else %>
          <%= button_to 'Ativar', active_dish_path(@dish), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <% end %>
        <%= link_to 'Adicionar porção', new_dish_dish_portion_path(@dish), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <%= link_to 'Editar', edit_dish_path(@dish), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
        <%= button_to 'Remover', dish_path(@dish), method: :delete,  class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900" %>
      </div>
    <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
  </div>
</section>