config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  resources :restaurants, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
    resources :tags, only: [ :new, :create ]
    resources :menus, only: [:new, :create, :show, :edit, :update ]
    resources :orders, only: [:index, :new, :create, :show ] 
    resources :workers, only: [ :index, :new, :create ]
  end

  resources :restaurant_schedules, only: [ :new, :create, :show, :edit, :update ]

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member 
    post 'active', on: :member
    resources :dish_portions, only: [ :new, :create, :show ] do
      resources :dish_previous_prices, only: [ :create ]
    end
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'inactive', on: :member
    post 'active', on: :member
    resources :beverage_portions, only: [ :new, :create, :show ] do 
      resources :beverage_previous_prices, only: [ :create ]
    end
  end

  resources :carts, only: [ :show ] do
    post 'add_dish', on: :member
    post 'remove_dish', on: :member
    post 'add_beverage', on: :member
    post 'remove_beverage', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :restaurants, param: :code, only: [ ] do
        resources :orders, param: :code, only: [ :index, :show ] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  belongs_to :admin
  has_one :restaurant_schedule
  has_many :dishes
  has_many :beverages
  has_many :tags
  has_many :menus
  has_many :orders
  has_many :workers

  before_validation :generate_code, on: :create
  
  validates :code, :cnpj, :admin, :email, uniqueness: true
  validates :brand_name, :corporate_name, :email, :cnpj, :telephone_number, :full_address, presence: true
  validates :email, format: {with: EMAIL_REGEX}
  validates :telephone_number, length: { minimum: 10, maximum: 11 }
  validate :cnpj_is_valid?


  private

  def cnpj_is_valid?    
    errors.add(:cnpj, 'não é válido') unless CNPJ.valid?(cnpj)   
  end


  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :auth_admin, only: [ :edit, :update ]
  before_action :authenticate_admin_or_user, only: [ :show ]
  before_action :register_a_restaurant, only: [ :show ]
  before_action :check_user_own_a_restaurant, only: [ :new, :create ]
  before_action :set_and_check_restaurant, only: [ :show ]
  before_action :set_and_check_restaurant_for_admin, only: [ :edit, :update ]
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.admin = current_admin
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurante cadastrado'
    else
      @restaurant.admin = nil
      flash.now[:alert] = 'Restaurante não cadastrado'
      render 'new', status: :unprocessable_entity
    end
  end

  def show    
    if DateTime.now.wday == 1 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.mon_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.mon_open.strftime("%H:%M")
      @status = 'Aberto'
    elsif DateTime.now.wday == 2 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.tue_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.tue_open.strftime("%H:%M")
      @status = 'Aberto' 
    elsif DateTime.now.wday == 3 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.wed_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.wed_open.strftime("%H:%M")
      @status = 'Aberto' 
    elsif DateTime.now.wday == 4 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.thu_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.thu_open.strftime("%H:%M")
      @status = 'Aberto' 
    elsif DateTime.now.wday == 5 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.fri_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.fri_open.strftime("%H:%M")
      @status = 'Aberto' 
    elsif DateTime.now.wday == 6 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.sat_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.sat_open.strftime("%H:%M")
      @status = 'Aberto' 
    elsif DateTime.now.wday == 0 && DateTime.now.strftime("%H:%M") < @restaurant.restaurant_schedule.sun_close.strftime("%H:%M") && DateTime.now.strftime("%H:%M") > @restaurant.restaurant_schedule.sun_open.strftime("%H:%M")
      @status = 'Aberto' 
    else
      @status = 'Fechado'
    end
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(current_admin.restaurant), notice: 'Horário de Restaurante editado'
    else
      flash.now[:alert] = 'Horário de Restaurante não editado'
      render 'edit', status: :unprocessable_entity
    end      
  end

  def search
    @search = params[:query]
    @tag = current_admin.restaurant.tags.find_by(description: "#{@search}" )
    @dishes = current_admin.restaurant.dishes.where("name LIKE ? OR description LIKE ?", "%#{@search}%", "%#{@search}%" )
    @beverages = current_admin.restaurant.beverages.where("name LIKE ? OR description LIKE ?", "%#{@search}%", "%#{@search}%" )
  end
  
  private 
  def check_user_own_a_restaurant
    unless current_admin.restaurant.nil?
      return redirect_to restaurant_path(current_admin.restaurant) unless current_admin.restaurant.restaurant_schedule.nil?
      redirect_to restaurant_path(new_restaurant_schedule_path)
    end
  end

  def authenticate_admin_or_user
    redirect_to root_path unless current_admin || current_user
  end

  def set_and_check_restaurant
    @restaurant = Restaurant.find(params[:id])
    if (current_admin && @restaurant != current_admin.restaurant) || (current_user && @restaurant != current_user.restaurant)
      redirect_to root_path, alert: "Você não possui acesso a este cardápio"
    end
  end

  def set_and_check_restaurant_for_admin
    @restaurant = Restaurant.find(params[:id])
    if @restaurant != current_admin.restaurant
      redirect_to restaurant_path(current_admin.restaurant), alert: "Você não possui acesso a este restaurante"
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:corporate_name, :brand_name, :cnpj,
                        :email, :telephone_number, :full_address  )
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: @restaurant, class: "space-y-8") do |f| %>
  <div>
    <%= f.label :corporate_name, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :corporate_name, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :brand_name, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :brand_name, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :cnpj, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :cnpj, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :full_address, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :full_address, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :telephone_number, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.text_field :telephone_number, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.label :email, class: "block mb-2 text-sm font-medium text-black-900 dark:text-black-300" %>
    <%= f.email_field :email, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" %>
  </div>
  <div>
    <%= f.submit 'Próximo', class: "w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<section class="bg-slate-500">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Editar Restaurante</h2>
      <% if @restaurant.errors.any? %>
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= render 'form' %>  
  </div>
</section>

app/views/restaurants/new.html.erb
<section class="bg-slate-500">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Novo Restaurante</h2>
      <% if @restaurant.errors.any? %>
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= render 'form' %>  
  </div>
</section>

app/views/restaurants/search.html.erb
<h1>Resultados da Busca por: <%= @search %></h1>

<div class="m-4 relative overflow-x-auto flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
               <% if @dishes.present? && @beverages.present?  %>
                <th scope="col" class="px-6 py-3">
                  Opções encontradas: <%= @dishes.count + @beverages.count %>
                </th>
               <% elsif @dishes.present? %>
                <th scope="col" class="px-6 py-3">
                  Opções encontradas: <%= @dishes.count%>
                </th>
               <% elsif @beverages.present? %>
                <th scope="col" class="px-6 py-3">
                  Opções encontradas: <%= @beverages.count%>
                </th>
               <% elsif @tag.dishes.present? %>
                <th scope="col" class="px-6 py-3">
                  Opções encontradas: <%= @tag.dishes.count%>
                </th>
            </tr>
          <% end %>
        </thead>
        <tbody>
          <% if @dishes.present? %>
            <% @dishes.each do | dish |%>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <%= link_to dish.name, dish_path(dish), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
                <td class="px-6 py-4">
                  <%= link_to 'Editar', edit_dish_path(dish), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
            <% end %>
          <% end %>
          <% if @beverages.present? %>
            <% @beverages.each do | beverage |%>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <%= link_to beverage.name, beverage_path(beverage), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
                <td class="px-6 py-4">
                  <%= link_to 'Editar', edit_beverage_path(beverage), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
            <% end %>
          <% end %>
          <% if @tag.present? %>
            <% @tag.dishes.each do | dish |%>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <td class="px-6 py-4">
                  <%= link_to dish.name, dish_path(dish), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
                <td class="px-6 py-4">
                  <%= link_to 'Editar', edit_dish_path(dish), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
            <% end %>
          <% end %>
        </tbody>
    </table>
    <br/>    
  <div>  

app/views/restaurants/show.html.erb
<section class="bg-slate-500">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white">Restaurante: <%= @restaurant.brand_name %></h2>
    <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-blue"><%= @status %></p>    
    <dl>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Razão Social:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @restaurant.corporate_name %></dd>
      <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Endereço Completo:</dt>
      <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @restaurant.full_address %></dd>
    </dl>
    <dl class="flex items-center space-x-6">
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">CNPJ:</dt>
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @restaurant.cnpj %></dd>
      </div>
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Telefone:</dt>
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @restaurant.telephone_number %></dd>
      </div>
      <div>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">E-mail:</dt>
        <dd class="mb-4 font-light text-black-500 sm:mb-5 dark:text-black-400"><%= @restaurant.email %></dd>
      </div>
    </dl>
      <div class="flex items-center space-x-4">
        <%= link_to 'Meu Hórario', restaurant_schedule_path(@restaurant.restaurant_schedule), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900"%>
        <%= link_to 'Editar', edit_restaurant_path(@restaurant), class: "inline-flex items-center text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-900"%>
      </div>
    <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
  </div>
</section>